pipeline {
    agent {
        node {
            label 'jenkins-slave7.yvu.ch'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'echo clean build'
                sh '(cd Gadgeothek; ./gradlew clean build assembleRelease)'
            }
            post {
                always {
                    junit 'Gadgeothek/app/build/test-results/**/*.xml'
                }
            }
        }
        stage('End2End Tests') {
            steps {
                sh 'echo End2End Tests'
                sh '(cd Gadgeothek; ./gradlew connectedAndroidTest)'
            }
        }
        stage('Zipalign') {
            steps {
                sh 'echo Zipalign'
                sh '(cd Gadgeothek; zipalign -v -p 4 sgadgeothek.apk sgadgeothek-unsigned-aligned.apk )'
            }
        }
        stage('Publish') {
            steps {
                sh 'echo Publish'
            }
        }
    }
}